[v1]
"buck2 0.1.0 (git+https://github.com/facebook/buck2.git#e427ac31dcbc5e1ede1ec9fdee20ae39eba37bed)" = ["buck2"]
"cargo-binstall 1.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-binstall"]
"cargo-bloat 0.11.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bloat"]
"cargo-edit 0.12.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-expand 1.0.34 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-generate 0.18.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-generate"]
"cargo-leptos 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-leptos"]
"cargo-watch 8.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"cross 0.2.4 (git+https://github.com/cross-rs/cross#f0190b0c0fd8fc354d9b0fad61c06bf0f29be277)" = [
    "cross",
    "cross-util",
]
"tailspin 1.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["spin"]
"tauri-cli 1.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tauri"]
