"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Tom Verelst"
email = "664136+tomverelst@users.noreply.github.com"

[ui]
editor = "nvim"

[git]
push-new-bookmarks = true
# Prevent pushing work in progress or anything explicitly labeled "private"
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"
