"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Tom Verelst"
email = "664136+tomverelst@users.noreply.github.com"

[ui]
editor = "nvim"

[git]
push-new-bookmarks = true
